[build]
  functions = "functions"  # Папка с функциями

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/django_function/admin/:splat"  # Имя функции — django_function
  status = 200
  force = true

[[redirects]]
  from = "/tests/*"
  to = "/.netlify/functions/django_function/tests/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200